<a href="https://colab.research.google.com/github/taniyaajain/Ecommerce_project/blob/main/Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("Order_Sales_Data_500_Records.csv")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Sub_Category,Product_Name,Quantity,Price,Discount,Payment_Mode,Shipping_Cost,Profit
0,ORD10002,2025-10-07,CUST1023,Customer 109,North,Delhi,Home,Kitchen,Mixer Grinder,4,2786,25,COD,386,7972.00
1,ORD10003,2025-12-26,CUST1140,Customer 108,North,Delhi,Electronics,Mobile,iPhone,1,74363,5,Card,372,70272.85
2,ORD10004,2025-03-21,CUST1056,Customer 87,South,Kochi,Home,Kitchen,Mixer Grinder,3,11938,15,UPI,182,30259.90
3,ORD10005,2025-08-24,CUST1138,Customer 32,North,Delhi,Clothing,Men,Men Jeans,6,2872,10,COD,413,15095.80
4,ORD10006,2025-01-24,CUST1059,Customer 75,West,Mumbai,Home,Kitchen,Cookware Set,6,9959,5,Card,75,56691.30

In [ ]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Region           0
City             0
Category         0
Sub_Category     0
Product_Name     0
Quantity         0
Price            0
Discount         0
Payment_Mode     0
Shipping_Cost    0
Profit           0
dtype: int64

In [ ]:
df['Discount'].fillna(0, inplace=True)

/tmp/ipykernel_1832/586566192.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount'].fillna(0, inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [ ]:
df['Revenue'] = df['Quantity'] * df['Price'] * (1 - df['Discount']/100)

In [ ]:
df['Month'] = df['Order_Date'].dt.month

In [ ]:
df['Revenue'].sum()

np.float64(29921495.25)

In [ ]:
df.groupby('Product_Name')['Revenue'].sum().sort_values(ascending=False).head(10)

Product_Name
Redmi Note         3703556.30
Boat Headphones    2983085.95
HP Pavilion        2624043.40
OnePlus Nord       2592277.05
Sony Headphones    2415837.55
iPhone             2181877.60
JBL Headphones     1812757.40
Lenovo IdeaPad     1741188.25
Acer Aspire        1730511.60
Dell Inspiron      1687447.30
Name: Revenue, dtype: float64

In [ ]:
df.groupby('Region')['Revenue'].sum()

Region
East     8978340.35
North    6033225.30
South    8099312.80
West     6810616.80
Name: Revenue, dtype: float64

In [ ]:
df.groupby('Month')['Revenue'].sum()

Month
1     2300289.45
2     1934230.20
3     2755898.75
4     2387324.85
5     3460105.80
6     2363003.60
7     2136037.25
8     3356242.65
9     2229423.65
10    1879177.35
11    1757489.50
12    3362272.20
Name: Revenue, dtype: float64

In [ ]:
df['Customer_ID'].value_counts()
Customers with more than 1 order = Repeat customers

SyntaxError: invalid syntax (49301292.py, line 2)

In [ ]:
df.groupby('Payment_Mode')['Revenue'].sum()

Payment_Mode
COD      8013547.05
Card    10720206.50
UPI     11187741.70
Name: Revenue, dtype: float64